# Generated by Django 4.2.5 on 2025-04-30 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('st', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='consultant_cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_reçues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='domaine',
            field=models.CharField(blank=True, choices=[('informatique', 'Informatique'), ('comptabilite', 'Comptabilité'), ('juridique', 'Juridique')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='est_publique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demande',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('offre_soumise', 'Nouvelle offre reçue'), ('offre_acceptee', 'Offre acceptée'), ('offre_refusee', 'Offre refusée'), ('nouvelle_demande', 'Nouvelle demande'), ('message_recu', 'Message reçu')], max_length=50),
        ),
    ]
