# Generated by Django 4.2.5 on 2025-04-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0006_demande_consultant_cible_demande_domaine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='domaine',
            field=models.CharField(blank=True, choices=[('informatique', 'Informatique'), ('comptabilite', 'Comptabilité'), ('juridique', 'Juridique')], max_length=50, null=True),
        ),
    ]
