# Generated by Django 4.2.5 on 2025-05-01 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('st', '0007_profil_domaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='statut_validation',
        ),
        migrations.AddField(
            model_name='demande',
            name='consultants_attribues',
            field=models.ManyToManyField(blank=True, related_name='demandes_attribuees', to=settings.AUTH_USER_MODEL),
        ),
    ]
