# Generated by Django 4.2.5 on 2025-05-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0008_remove_demande_statut_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='etat_avancement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
    ]
