# Generated by Django 4.2.5 on 2025-05-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0009_offre_etat_avancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='odoo_partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('consultant', 'Consultant'), ('gestionnaire', 'Gestionnaire'), ('administrateur', 'Administrateur')], default='entrepreneur', max_length=20),
        ),
    ]
