# Generated by Django 4.2.5 on 2025-05-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0010_profil_odoo_partner_id_alter_profil_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='facture_odoo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
