# Generated by Django 4.2.5 on 2025-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0011_offre_facture_odoo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='bon_de_commande_odoo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
