# Generated by Django 4.2.5 on 2025-05-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0012_offre_bon_de_commande_odoo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='bon_de_commande_odoo_id',
            new_name='bon_commande_odoo_id',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='facture_odoo_id',
        ),
    ]
