# Generated by Django 4.2.5 on 2025-05-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0013_rename_bon_de_commande_odoo_id_offre_bon_commande_odoo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='adresse_facturation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='adresse_livraison',
            field=models.TextField(blank=True, null=True),
        ),
    ]
